# Generated by Django 3.2.5 on 2022-11-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20221120_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='BDI_score',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='ISI_score',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
