# Generated by Django 3.2.5 on 2022-11-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20221120_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='SB_questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='new_user',
            field=models.IntegerField(default=1),
        ),
    ]
