# Generated by Django 3.2.5 on 2022-11-20 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20221120_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='SB_score',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
